server:
  port: 8082
  servlet:
    context-path: /product

feign:
  basePackages: con.wt.test.seata

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: product
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: product
        instance-id: ${spring.application.name}:${spring.cloud.consul.host}:${server.port}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        heartbeat:
          enabled: true
        register: true

debug: true
