server:
  port: 8081
  servlet:
    context-path: /order

feign:
  basePackages: com.wt.test.seata

mybatis-plus:
  basePackages: com.wt.test.seata.*.mapper
  dbType: mysql
  mapper-locations: classpath:mapper/**/*Mapper.xml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1nnjhvq3tra324d.mysql.rds.aliyuncs.com/open_gateway?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: v7#ROHq7JmKD
    hikari:
      pool-name: gmc-open-gateway
      minimum-idle: 10 #最小空闲连接数量
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20 #连接池最大连接数，默认是20
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: order
        instance-id: ${spring.application.name}:${spring.cloud.consul.host}:${server.port}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        heartbeat:
          enabled: true
        register: true

  main:
    allow-bean-definition-overriding: true

debug: true
