server:
  port: 8081
  servlet:
    context-path: /order

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: order
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        service-name: order
        instance-id: ${spring.application.name}:${spring.cloud.consul.host}:${server.port}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        heartbeat:
          enabled: true

debug: true
